version: '3.9'
services:
  angular-client:
    build: ./angular_client
    ports:
      - "80:80"
    depends_on:
      - websocket-server

  websocket-server:
    build: ./server
    ports:
      - "8080:8080"